import { Product } from '../types/Product';

/**
 * Simulated real product inventory from Seeed Studio
 * This can be replaced with live API or DB later
 */
export async function fetchSeeedProducts(): Promise<Product[]> {
  return [
    {
      name: 'Soil Moisture Sensor v2.0',
      price: 12.99,
      priceUSD: 12.99,
      quantity: 18,
      url: 'https://www.seeedstudio.com/Soil-Moisture-Sensor-v2.html',
      description: 'Measures soil water content for irrigation systems',
      tags: ['soil', 'moisture', 'irrigation', 'drought'],
    },
    {
      name: 'Analog pH Sensor Kit',
      price: 26.5,
      priceUSD: 26.5,
      quantity: 10,
      url: 'https://www.seeedstudio.com/Analog-pH-Sensor-Kit.html',
      description: 'Reads pH levels for soil and hydroponic systems',
      tags: ['ph', 'soil', 'acidity', 'hydroponics'],
    },
    {
      name: 'Air Humidity Sensor',
      price: 9.99,
      priceUSD: 9.99,
      quantity: 25,
      url: 'https://www.seeedstudio.com/Air-Humidity-Sensor.html',
      description: 'Measures ambient air humidity for crop and climate applications',
      tags: ['humidity', 'climate', 'greenhouse', 'drought'],
    },
    {
      name: 'Temperature and Humidity Sensor',
      price: 11.5,
      priceUSD: 11.5,
      quantity: 30,
      url: 'https://www.seeedstudio.com/Grove-Temperature-and-Humidity-Sensor.html',
      description: 'Monitors environmental conditions to detect frost or heat risks',
      tags: ['temperature', 'humidity', 'frost', 'heat'],
    },
    {
      name: 'Solar Power Management Module',
      price: 18.49,
      priceUSD: 18.49,
      quantity: 12,
      url: 'https://www.seeedstudio.com/Solar-Power-Management-Module.html',
      description: 'Manages solar input for off-grid or remote ag-tech deployments',
      tags: ['solar', 'power', 'off-grid', 'drought', 'rural'],
    },
    {
      name: 'Multi-Channel Relay Module v1.0',
      price: 14.75,
      priceUSD: 14.75,
      quantity: 15,
      url: 'https://www.seeedstudio.com/Relay-Module.html',
      description: 'Automates irrigation, heating, or ventilation systems',
      tags: ['automation', 'relay', 'greenhouse', 'climate'],
    },
    {
      name: 'LoRa Radio Module (868/915 MHz)',
      price: 16.25,
      priceUSD: 16.25,
      quantity: 20,
      url: 'https://www.seeedstudio.com/LoRa-Radio-Module-915MHz.html',
      description: 'Enables long-range wireless communication for sensor networks',
      tags: ['lora', 'communication', 'remote', 'connectivity'],
    },
    {
      name: 'Grove - Water Flow Sensor',
      price: 8.99,
      priceUSD: 8.99,
      quantity: 20,
      url: 'https://www.seeedstudio.com/Grove-Water-Flow-Sensor.html',
      description: 'Monitors water usage and flow for smart irrigation systems',
      tags: ['water', 'irrigation', 'flow', 'drought'],
    },
    {
      name: 'Grove - CO2 Sensor',
      price: 22.0,
      priceUSD: 22.0,
      quantity: 18,
      url: 'https://www.seeedstudio.com/Grove-Gas-Sensor-MH-Z16-CO2.html',
      description: 'Measures carbon dioxide levels for enclosed environments',
      tags: ['co2', 'greenhouse', 'air', 'climate'],
    },
    {
      name: 'Barometric Pressure Sensor (BMP280)',
      price: 6.95,
      priceUSD: 6.95,
      quantity: 25,
      url: 'https://www.seeedstudio.com/BMP280-Barometric-Pressure-Sensor.html',
      description: 'Monitors barometric pressure for weather prediction',
      tags: ['pressure', 'weather', 'altitude', 'climate'],
    },
    {
      name: 'UV Sensor (GUVA-S12SD)',
      price: 5.99,
      priceUSD: 5.99,
      quantity: 25,
      url: 'https://www.seeedstudio.com/UV-Sensor-GUVA-S12SD.html',
      description: 'Detects UV radiation for crop and skin safety applications',
      tags: ['uv', 'solar', 'radiation', 'climate'],
    },
    {
      name: 'Soil Temperature Sensor',
      price: 13.5,
      priceUSD: 13.5,
      quantity: 15,
      url: 'https://www.seeedstudio.com/Grove-Soil-Temperature-Sensor.html',
      description: 'Monitors underground temperatures for root and frost analysis',
      tags: ['soil', 'temperature', 'frost', 'roots'],
    },

    // ✅ Newly Added Products for Bundle Compatibility
    {
      name: 'Irrigation Pump Controller',
      price: 22.75,
      priceUSD: 22.75,
      quantity: 10,
      url: 'https://www.seeedstudio.com/Irrigation-Pump-Controller.html',
      description: 'Controls water pumps for automated irrigation',
      tags: ['irrigation', 'pump', 'controller'],
    },
    {
      name: 'Solar Water Pump Kit',
      price: 48.99,
      priceUSD: 48.99,
      quantity: 8,
      url: 'https://www.seeedstudio.com/Solar-Water-Pump-Kit.html',
      description: 'Solar-powered water pump system for off-grid irrigation',
      tags: ['solar', 'pump', 'irrigation', 'drought'],
    },
    {
      name: 'Environmental Sensor Kit',
      price: 34.99,
      priceUSD: 34.99,
      quantity: 15,
      url: 'https://www.seeedstudio.com/Environmental-Sensor-Kit.html',
      description: 'Full suite of climate sensors for agricultural applications',
      tags: ['humidity', 'temperature', 'environment'],
    },
    {
      name: 'Temperature Sensor',
      price: 10.99,
      priceUSD: 10.99,
      quantity: 20,
      url: 'https://www.seeedstudio.com/Temperature-Sensor.html',
      description: 'Measures ambient temperature accurately',
      tags: ['temperature', 'heat', 'frost'],
    },
    {
      name: 'Weather Station Kit',
      price: 64.95,
      priceUSD: 64.95,
      quantity: 12,
      url: 'https://www.seeedstudio.com/Weather-Station-Kit.html',
      description: 'Comprehensive weather monitoring setup',
      tags: ['weather', 'climate', 'frost'],
    },
    {
      name: 'Smart Shade Controller',
      price: 37.5,
      priceUSD: 37.5,
      quantity: 25,
      url: 'https://www.seeedstudio.com/Smart-Shade-Controller.html',
      description: 'Automates shading to protect crops from heat',
      tags: ['shade', 'heat', 'climate', 'automation'],
    },
    {
      name: 'Ultrasonic Pest Repeller',
      price: 19.99,
      priceUSD: 19.99,
      quantity: 22,
      url: 'https://www.seeedstudio.com/Ultrasonic-Pest-Repeller.html',
      description: 'Repels pests using ultrasonic frequencies',
      tags: ['pests', 'insects', 'repellent'],
    },
    {
      name: 'Insect Monitoring Trap',
      price: 8.5,
      priceUSD: 8.5,
      quantity: 30,
      url: 'https://www.seeedstudio.com/Insect-Monitoring-Trap.html',
      description: 'Tracks insect activity in crop zones',
      tags: ['monitoring', 'pests', 'insects'],
    },
    {
      name: 'Soil Testing Kit',
      price: 14.25,
      priceUSD: 14.25,
      quantity: 16,
      url: 'https://www.seeedstudio.com/Soil-Testing-Kit.html',
      description: 'Tests various soil properties including pH and nitrogen',
      tags: ['soil', 'testing', 'acidity'],
    },
    {
      name: 'Water Level Sensor',
      price: 9.99,
      priceUSD: 9.99,
      quantity: 25,
      url: 'https://www.seeedstudio.com/Water-Level-Sensor.html',
      description: 'Monitors water levels for flood detection',
      tags: ['water', 'flood', 'monitoring'],
    },
    {
      name: 'Drainage Control Valve',
      price: 17.95,
      priceUSD: 17.95,
      quantity: 18,
      url: 'https://www.seeedstudio.com/Drainage-Control-Valve.html',
      description: 'Regulates drainage to prevent flooding',
      tags: ['drainage', 'flood', 'control'],
    },
  ];
}
